# Generated by Django 3.2.9 on 2021-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_receita_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
