# Generated by Django 3.2.9 on 2021-11-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_medicamento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='medicamento',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('horario', models.DateField()),
                ('Medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='medicacoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.horario'),
        ),
    ]
