# Generated by Django 3.2.9 on 2021-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211130_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='medicacoes',
        ),
        migrations.AddField(
            model_name='receita',
            name='medicacoes',
            field=models.ManyToManyField(to='app.Medicamento'),
        ),
    ]
