# Generated by Django 3.2.9 on 2021-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='medicacoes',
            field=models.ManyToManyField(to='app.Medicamento'),
        ),
    ]
