# Generated by Django 3.2.9 on 2021-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_receita_medicacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='cronograma',
            field=models.TextField(null=True),
        ),
    ]
